### ISSUE TITLE
README contains link to bitbucket

### ISSUE THREAD

**Issue by wdroz** [InternetOfUs/components-documentation#1]
In the README, we still a links like <http://swagger.u-hopper.com/?url=https://bitbucket.org/wenet/wenet-components-documentation/raw/master/sources/wenet-personal_context_builder-openapi.json>

We should replace them with something like <http://swagger.u-hopper.com/?url=https://github.com/InternetOfUs/components-documentation/raw/master/sources/wenet-personal_context_builder-openapi.json>

But this currently fail because of the CORS rules.

**Comment by carlocaprini** [comment]
@wdroz thanks for pointing this out. We will make sure to update the links so that they can be correctly used. 

@StefanoTavonatti for sure we should be updating the links (stop using the bitbucket ones and move to the GitHub ones). I am also wondering whether we should stop using the _u-hopper swagger_ endpoints. 🤔
